---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: panel
  namespace: pterodactyl
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gameservers.f9.casa`)
      kind: Rule
      services:
        - name: panel
          port: 80
      middlewares:
        - name: default-headers
          namespace: default
        - name: panel-headers
          namespace: pterodactyl

