apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    volumeHandle: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: mariadb
spec:
  storageClassName: longhorn-static
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
  volumeName: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
  name: mariadb
  namespace: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        app.kubernetes.io/name: mariadb
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - image: lscr.io/linuxserver/mariadb
          name: mariadb
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          env:
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "022"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/London
          volumeMounts:
            - mountPath: /config
              name: data
      hostname: mariadb
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: mariadb 
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.10.202
  ports:
    - name: "mariadb"
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
