kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgresql-secret
    namespace: postgresql
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AIf9WpTPUlv1AHI3e+YUQsRAWqzvbHwgGDugryHgcNZizrShmr/H6A==,iv:bkbowiT1lDMX4hlmEA+8R4Qp95GYsdeKdM5JenhLsQA=,tag:T0RBiFdkyZMaN4Bq3QWyLg==,type:str]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:TwXPyZEF/3BBjxAv9w==,iv:nlftINjx53dqORYOeSZotGSW+HzDGc4kR1QDmTVtArE=,tag:/37g1bGLwdxKHkldLMwIdg==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:/Xl0PiauN00=,iv:J2z/3fBSTdQdZb6iJTNlKbKdplGgrJvaai+7DQuyj9E=,tag:XHOPomv9zmvcqlVCqBb42A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbTNKaFdBalhHaDg1YlJX
            QWJpUlM1UE5TZVJhSWE0Z01XR3gyUENHSWtjCjlZRzNpRThXWUJsVlRsOWhXMGdE
            Rmdrc01hbnBlQnUyS3M5N0RidDcwQXcKLS0tIHA3WWFLZG9vVk5kbUtCNjlJNWVP
            TDUxQ3E4Wk1lbE05M2dwMXBjdTFqVU0KDGyUbLORfRWccECQjgujaWc0qKv8tf/6
            VG+ZXzYrwvQ2M8GvBK77FZB0Q+C05/XinfrpIV+m7+nZkyKVOOY/MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T21:09:15Z"
    mac: ENC[AES256_GCM,data:mhZ9CLC6gHXtnF9b3KO6mwBt8bgvRizJz3UmJQ/qaZPdsILpfAik3MU+j1fspqcNET4bn7t5ygh3hzoDQied5OC5WQ+Tb48dPwCF862i7emwBh1llHczSX6AzXC/zqRy5ebq5sn+LOghRTDpGPlwJCO47WF3wmSXaYwq2KJYRAQ=,iv:KGWr/xWsTyLeQFjQXanLHHIx2akx4olVhbP9Zqb1Jbk=,tag:GVQwzeF5hhakLXVB9ndPwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: b84f2560f1998cd63005938bae046f8d31c2b854e9e0aa88bb7f0744bddc44ae
