kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgresql-secret
    namespace: postgresql
stringData:
    POSTGRES_PASSWORD: "Password for Postgres"
    PGADMIN_DEFAULT_EMAIL: admin@domain.tld
    PGADMIN_DEFAULT_PASSWORD: "PGAdmin Password"
