kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: redis-secret
    namespace: redis
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:BUfvvJ0izLvm0tTRZw==,iv:Qs9Jyhx6RIGWYk8Dck0r2H685H+hUq+XXuwsKUX3rxk=,tag:xZxWyFMeip5eSzGGm5sIUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWitpVTNUMGtHbXdSdGdN
            ZWp3QTVQRGptbGlRbFVLNjgrZm55QytvZ25ZCmNSRTYzakd1anFCalNOQVE3U1ZT
            MDAzbG04UTNwWWpyaFBMeWsrOUJFR00KLS0tIEkyV1RRSGRKaGtCaE91cGt4eXFm
            NzlyU1lkU1NsZWFwSlZoa2l1aVNMYVUKZqrZ+kxvJW2MR/uH6zct87tGCETnLSzw
            nAv1iIgaGfCO1rHpx27NF/h4DzZxcbK8Wu/om6YGXOozImLrZauwFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T21:09:15Z"
    mac: ENC[AES256_GCM,data:uHJzE7pGPRDCgTra19sPpqQcYyMxUlXXAdW+hRcVSPi50XLE4kiinIqaUY1AuV/dmNM0dGhdr36RLnPKvMyurcS+OsBAN6zTPhlj5tk5piolPbeSxEd642lTwEgTO7A29U594UjZBtji8pH7Nt2v8GDvnJKtp3idQ3JUsCh6YAg=,iv:HeEhMJkEDh+7LScxRdQAf6cukfeerZRYXpNTjunTuRA=,tag:nBN37MR7+apscpGQamtdMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: a3202c02ad984efd3b4b6c2be3f16121a5f44b36bfe30cd971c4b53aece1a469
