---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: outline
    app.kubernetes.io/instance: outline
    app.kubernetes.io/name: outline
  name: outline
  namespace: outline
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      labels:
        app: outline
        app.kubernetes.io/name: outline
    spec:
      nodeSelector:
        worker: "true"
      containers:
      - image: docker.getoutline.com/outlinewiki/outline:latest
        name: outline
        envFrom:
          - secretRef:
              name: outline-secret
        env:
        - name: NODE_ENV
          value: "production"
        - name: URL
          value: "https://docs.f9.casa"
        - name: FILE_STORAGE
          value: "s3"
        - name: FORCE_HTTPS
          value: "false"
