kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: outline-secret
    namespace: outline
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:tAgS4nF4FOW1/Z/Cjmfb92fubD317C1QG8jKNg5GOviFhPMtFjKdGCsUVB6/lAGR7F0g8YmNjLbmQfwyknmdOg==,iv:0cskjUkR7K7YngW6dHHVAMziFXtC9pEH1Cnc48C8xb0=,tag:3KKz5d02iHtlGkj9xWJSgQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:rDNW8mpHKMwqzjxo6zhNk3TGdob+abWNxKmAcCr4mV8gkxz0fpkdDyvfJm7KUq7rJgYsiLJrxmB1nTiuNvYj4w==,iv:sPPwKbEzWpBLbS2mkofBNnRIZ+fBXO844pkofOY0sO4=,tag:Zq6a4Bk6H7YyN9A/Ql+zUg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:atbr2Yu6/qzltjcoMkNCTP9+xHSOFcOU9x5YTXw9xG5mmvzSMG8bpGuApoo/WYA9sXy4yBOkbroe2WRhLyBtPIaGbBJAn6/ZHBEit7ohm8bq2pkBdJc=,iv:kiLpMgatkCZt88b28xRzHAyhap/U8ybC92V56MKo4dA=,tag:DCTB3B7Uhu4hjOf9MydvfQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:i9vi8dBwPXjE3GE+UWBgD2qtMgtto9MSFqYqWGwar6iwduq1dGSGZ5vdYw==,iv:tMSvL/TMg+jfYBJ73fsRmnpUKYvgmjzKP8/eOZloEA4=,tag:jOBhJjJEIANcLbyspN+XFQ==,type:str]
    AWS_S3_UPLOAD_BUCKET_NAME: ENC[AES256_GCM,data:/W5JVOotOcAuyQ==,iv:Tn7o00UQZR7KSZ41XzBSrXEo6N1AiRRScIiPHXwIzO0=,tag:NbJFxJROgsGxL//hc93YDw==,type:str]
    AWS_S3_UPLOAD_BUCKET_URL: ENC[AES256_GCM,data:gygDWrfop6URf3NsjwOXh1Ly,iv:U1N7vRuZU3DW6erx44XWBKPU9Zbz5AVHej9a5J7qD0Q=,tag:gGYWM1oslm6PmumBq5DtXA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:yZqrgpw7Rchs,iv:80hjYm4BA1DN/uQaFj8djn4WB1RFeqwlniTO76SRdDE=,tag:UHl3MctUuoudDgTqSAZspQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FpdKAOmYDpL7aF7nU4iXfX/XLkOfwOKgh0w=,iv:wT1Jm4AB89LuWmACtpcard4AulnnUsXCHlB6GXYQdxc=,tag:I3w5jj0kCWWRBvsqR16/rg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FAt8W93/KSMJC974dIm5PuMhZIkFiL+ulrPF8mVGng1odpDrC70gUO8XGoIACxmWzE5FMgEvRXCcWyGcthMF6Q==,iv:O8sp2gfLCyl972ryF/Mn2mHmeRkJuffLn7BIj5ypclw=,tag:n+FsNFwRAEBGp6I2Etdi8Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:cie89hWv6r1P4f2ZI5+OHWQ7B7bWSpi7GIMCcQYSlLci3ghh9pAvIg==,iv:VPY8nP7i/NSsjcZhkZkWCTs+FOYJ70A8Zx6nYsKKSmg=,tag:BFJnRRGLwY6zcRYVcJyU+A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Lh/fF8Nn5/l8nx9X4gKAPjj1M2ClxfPfZof1jdZDh5nqMp1vpRAL0Q5tdNdbuQYwfooo6Tw8jPq9rA9P8OGSlWzCs1IB1YUxPivlmkB5SVrQpSloavpWclhI5GNYU+F9DBRv5yt4iCcBZnges4Ku4azLW4YDPVIkZ3Mkp9uLeXs=,iv:0yQ/u1QhRzfjlS0LchbJTS6QdnSqMjgipj02imtVNHQ=,tag:Pj5SoW+Oto0eNd94nKN8tQ==,type:str]
    OIDC_AUTH_URI: ENC[AES256_GCM,data:5n/pMZNkMnM/BvDFv6IHz7vZq9r2D5Amyhp0sir84dcqDuwCXwJyydpVvilD,iv:A1waSHLPd/EclC6TJtwbMK9qkHYvOX766thnMvNlDvo=,tag:deYErg00S83v2+l0w47l/w==,type:str]
    OIDC_TOKEN_URI: ENC[AES256_GCM,data:i8J/Fiq2F8HQPaR7KCMrxgdJeXDiHteCP2XcuMu6f0bP3fBmmXetXqA=,iv:RmDAS+d90ysUBwWSru1kuCbqGqGSxAuyqHVWl/nd0Mo=,tag:0AvSqtcDw5sjsU1jZmVycA==,type:str]
    OIDC_USERINFO_URI: ENC[AES256_GCM,data:OPIp1aUSQClsmDnNlBrYEZ5uqoTovxp+6fggmbQpbG6lE2EO5dlGNHCjyYQ=,iv:0ku9h22XCnBih1sQHqXRKaRO719ubqcStYYokzJ/TEw=,tag:y4Jg5aPvNI0BQcixa3JQ2g==,type:str]
    OIDC_LOGOUT_URI: ENC[AES256_GCM,data:RlY/E8fULwjHFSIMEPcXuvlw+/f7ahgknsenzq7xbQNqq4B1HSF6Pu4Adqx5oU+ILsyRAOAG7w==,iv:3W2IVO+HrFR0hzkVL/3gIG4GAqFrGmcv17GHeyl46fc=,tag:KaWhM3FUj4G+lfSE6gJHlg==,type:str]
    OIDC_USERNAME_CLAIM: ENC[AES256_GCM,data:Bn1uXxGDL1VD3nLJ3CpSYjsq,iv:9ZpjGKztcWC9ch/buivnv3KNR7mm97wMOmwj0SL8ULY=,tag:Jv17xPLnQG4+gGrOW0O5Kw==,type:str]
    OIDC_DISPLAY_NAME: ENC[AES256_GCM,data:SkrEZ5ci,iv:rd4wnatDgRXj7ncj+5yJ4yCLtajuSlOXqej6WSFD1S8=,tag:hHOOZlESeBgFHxwIqbYymw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:4pojbTnl5vuEoWfZWuk/6RlHuq4=,iv:kS8vrkSQ3uvpq+9U/oaJRATMeScMY1nlneG9HXI5UGM=,tag:v+V5lYoIb7ikkFpvPU4Wsw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:wVKGWZeiRWh52Vs=,iv:1kLl3hBwqzmg8dZgMXLPFoGK1Hs2oY9P/meWyaACEis=,tag:TLKcud8lhZwiGO7/rJaTEg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:+r4=,iv:0N3iZnEsDgddAtyi6jat6loY+A1bI2IZdDMEfsNAp7M=,tag:woPs7iBw8MKo3qzaCjl5eA==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:pDNn1u2pQB6l6otA,iv:icE12gfrgULIC51N1gX+3TJC47tkCMgLUJbtpe3tEoA=,tag:BxO6AiHj60c9Ue9ykKaWyA==,type:str]
    SMTP_REPLY_EMAIL: ENC[AES256_GCM,data:TYfWO7a8F+gQ06m3AOl/,iv:RX28tk48vhuYbtrtrINT4hzem8Pree5UvxZEDsRC3mw=,tag:zEry/Vqg9VMh36MSdwJnBQ==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:v7eX4d0=,iv:iph36vrHDTh6P07awNdFX2NGcCO97Bxe6pLCSQuVCy0=,tag:9UU6ebAKGuwKGnRwZFoo0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBienZSdUFzaUtGVXdGRSs2
            ekNsb3VlclR5TTlQSERNS1BNdWphSEJPbHpnCnorZ1NXT2lxU2FXY050TTJJRGNM
            TWVMNW50L1FHWmZHRFRaTnZlSVIvaGMKLS0tIG5ualNMM3Y4Qm84c1pucGtpcSsx
            QzU2NG9VZ09FOERPY2U2TnZqa1phbG8KejZUsdzgxzsjKl/tBAqWm4AibQK6ql7E
            EEw0kmQU7lbz2qkEpCBeVUaragBcje/k8ycsjWfvhgx0i2jDd8X2Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T15:40:14Z"
    mac: ENC[AES256_GCM,data:IwUBEllcgHCaSkzFI+GOPI3Lpm4Ww+QJBsCYGr4d5a283KO534p6uWYm8zMz8Tg5w06ZbWvFg+td1l0Ls232xkkPi+4IZuAaI4o0BRXuWmHSWA9MWS8JohngQbZHAsxsgTssmpqJjr7QnG0pbj+UR4HPATPYFCIH3xZe9Lz2WWU=,iv:Yc1xQrPMPj7abKGSBtcDJc6JLCYI8x85VzgN1NklYjA=,tag:qypypEg3WLmx0cDGjBeS2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: db37a7231cbace4d60d23b96556ed72395e1c82803688a29c40572eb15207f77
