kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    DATABASE_URL: postgresql://vaultwarden:POSTGRES_PASSWORD@postgresql.postgresql:5432/vaultwarden
    ADMIN_TOKEN: "Admin Token, ideally argon2 encrypted (https://argon2.online/)"
    YUBICO_CLIENT_ID: ""
    YUBICO_SECRET_KEY: ""
    SMTP_FROM: "vaultwarden@domain.tld"
