---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/name: authentik
  name: authentik
  namespace: authentik
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authentik
  template:
    metadata:
      labels:
        app: authentik
        app.kubernetes.io/name: authentik
    spec:
      nodeSelector:
        worker: "true"
      containers:   
        - name: authentik-server 
          args:
            - server
          envFrom:
            - secretRef:
                name: authentik-secret
          env:
            - name: AUTHENTIK_ERROR_REPORTING__ENABLED
              value: "false"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgresql.postgresql
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_REDIS__HOST
              value: redis.redis
            - name: TZ
              value: Europe/London
          image: ghcr.io/goauthentik/server:latest
          
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
            - containerPort: 389
              hostPort: 3389
              protocol: TCP
            - containerPort: 636
              hostPort: 6636
              protocol: TCP
          volumeMounts:
            - mountPath: /backups
              name: config
              subPath: backups
            - mountPath: /media
              name: config
              subPath: media
            - mountPath: /certs
              name: config
              subPath: certs
            - mountPath: /templates
              name: config
              subPath: templates      

        - name: authentik-worker
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-secret
          env:
            - name: AUTHENTIK_ERROR_REPORTING__ENABLED
              value: "false"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgresql.postgresql
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_REDIS__HOST
              value: redis.redis
            - name: TZ
              value: Europe/London
          image: ghcr.io/goauthentik/server:latest
          volumeMounts:
            - mountPath: /backups
              name: config
              subPath: backups
            - mountPath: /media
              name: config
              subPath: media
            - mountPath: /certs
              name: config
              subPath: certs
            - mountPath: /templates
              name: config
              subPath: templates
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: authentik

        - name: authentik-ldap
          envFrom:
            - secretRef:
                name: authentik-secret
          image: ghcr.io/goauthentik/proxy
      restartPolicy: Always