apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    volumeHandle: authentik
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik
  namespace: authentik
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 1Gi
  volumeName: authentik
  storageClassName: longhorn-static