kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authentik-secret
    namespace: authentik
    annotations: 
      kustomize.toolkit.fluxcd.io/reconcile: disabled
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: "Password for AUTHENTIK_POSTGRESQL"
    AUTHENTIK_REDIS__PASSWORD: "Password for AUTHENTIK_REDIS"
    AUTHENTIK_SECRET_KEY: "openssl rand -base64 60 | tr -d '\n'"