kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:cKYlytnTfISiUliWXRvehk8cS8Kkfe/nWsN7YbSZsAOsYqkSomiD6A==,iv:Ssa4U0NTFoP6SDTflpv8c/7VjklM4vbyoi0MOHg+t/A=,tag:T3+tre7tMoqjYoIyY2H8ug==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:JdYgu/TuHKGwZH+Lqw==,iv:w/OXHN5da/VWFMtzlmKEyaJzf9VVdvgYtYHH03nP9AE=,tag:zTeCK0LxPHDWrMFQe3QZ6A==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Hubo0qvShJjihGUyJEQjSfdKWq4/L1V/9lN6UGISK3ZYeearYRZ6u6DmdL1fpy9Xilc=,iv:B947uQpHqWxXaE+Od/HEbfQvekyPKy8/ApCUrozTxK4=,tag:4niytawgQ6xIsKqqJXk/0Q==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:0co1CUkx9nCPrgPcHZld6hO+QO0=,iv:WEezhqRMDwxkCfWP8XHbnl40ioFUZGYRFJvXmQb9eLQ=,tag:Zlb8/hi16I/xht+h8boLQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOGFKQjMydFhLRFlobnlo
            TmZmMEpIcWdLajVVVm5zcWhXYXM2ODI5UHlvCkMyd2tHUlh4cENhcVBpU1R6UWs1
            d1UzSDZweXd6emVqRDZGckJ3c0E4LzgKLS0tIExCNUVSWDF4Z2pqVUdvRElxeXVG
            TnJUd3gyUzMwUGFRMjB6by9tbXo3bW8KScOynktdtzGtbe97/twtOVCMDk53eVDb
            2dwEBcE5fzxEOH9pVhP1b4z5Q0QiqFHMhH4VFL8rO4Y4IAwkqTaarg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T15:40:09Z"
    mac: ENC[AES256_GCM,data:9PNhCZLyQ6EN64Hl9liu44oXeRJGBnnbwXat5KmL6U15E27wsG36+84SjSI0xYR22Q/rNWF0hR4ZHXZslwu7qbODTNOyGO2LSZL6pjsju4iJcJxqtcZct+fPHSECDlYZQzrPyaHSHVoet6lJgdH4BvNsaCvBbLnwnaQmUPbqBdM=,iv:Qk799nrncc03hpQd6ZuMbXaicg9oSiAikUKGq+qcUGc=,tag:t30x8ZaCfmdNuytI5bmxIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 295fd45074bea4b7b96d5e22efda1a9946973ab4cd540fca265a775b34166f78
