kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:jU2IX9dklc+3MNbzTJIbKY2TmsdLE5T/kZvEQ7aEHZQy/g75rfVK8g==,iv:i9sZdIMyg65PooyI9w30vha4vJYMmJZHHJmUlCAYuqA=,tag:w4/PkVO6LHp4omA0D/FmNA==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:5oM+EHRWAxYoIcZMCg==,iv:bEGVfHA9C9JHxhVJvaGkFGAcmhBDTKk+mgTdG9j2LQk=,tag:57BXtv/PaSr6aYBc01sAog==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:9/rPHIM6aVDxQjJLxU2aDRUZ0KpkxocuNnuw1e4Qs5Izv8YwGCuzuJcANDR6PcwG0KE=,iv:gaU4GS4WvPaa9tBLoYe8nvNAYseGbttvdkDl8dEuB2Q=,tag:nenLchZBkybA84/x4yURqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dnpkSHpGZmpTZElXaWNa
            OUsrOCtkeERHeUNXSWhXb25mR3hkS0l3R1RzCmFLaWdsc0hSS2Ztc1NWWmlzTktl
            NjBrRTJmZE1IQzF6SExmR0cxVHFuMG8KLS0tIDE0K1crWDlScXdMUUtkVkNQR2ts
            ZDBJbVBzVE9iM25uVjdZaTNHTGY0VnMKfFPKm/boaw97gfRfjrn8LX02heC2AzvH
            uiFHQW4Mj9tYwrSQT607dUioLCtsIjuPi4G8kPaaubfkUZp14Q4gqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T21:09:11Z"
    mac: ENC[AES256_GCM,data:wr0iOgYlrxMySduPMR/lgdnlLQcwrfF5GajVEb11s1SUH06ezlb7TCqh8a5IlV0wc08oWT5h2TO6iOIQzWIdkyHccU0zns9KkMSIiApb3vhMrajAudevFEBIUklL0jzdTaOIF8SLOFRNljvBh1i/c5E5Wp2eiwoApAZGIpiQlFA=,iv:8MOrJYoXjqfxGtd4J4mxZ3cElw4xcocbbhHIF8eNy24=,tag:hUnN6pmt+hICWR3f49n52g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: fd3cbdb95587aa2a622e4b97ae52057a6990fe299c7620045d5064e89cb5f77d
