---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentik-server
  name: authentik-server
  namespace: authentik 
spec:
  ports:
  - name: web-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: authentik-server