kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: pterodactyl-secret
    namespace: pterodactyl
stringData:
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:Fk7g/ON3gtBu9ztYpjJQsY52KUPKiT4=,iv:otnoPhTAfJyWS7+Jwoz8NreHws6CY6Pkz1eX6AUqdQ4=,tag:I/RC3+b3npA0BJ1K947ljg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:PAcf4CGafziIgVndQg==,iv:Y1QGheB1wV1YFoLqhd0WXx/GOoKFc7n45+PnLqqWPRI=,tag:bpKcyNWxxGCzuLDl55NV1g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:i3uFSYM7iYIPVujH7wmLnG1aUBhNl1E=,iv:whxncjFoCW0lIMg0or0q0BGtA2lzcqr1CMjVvDhFZoE=,tag:5XxrNGIakzdzEheWSSdRug==,type:str]
    APP_KEY: ENC[AES256_GCM,data:mGpMsGCTQ2TErmGbRWHEO2BpQhnBsns7mcTUYQ91a2g=,iv:n6CpbolrSSdxpVgrXhwZtuI2UJ2GSZ8Y9nTxg5gacI4=,tag:sTlD3LPJC7VjS0SzoTpmaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ek1ZcGY4Q1FIKyt3RlRY
            NGJobm00YXYrNXVqRHJibGVYd2IvbVVwTWhNCi9SaE1vRFhmV1Z4NHpRL0o3SXdB
            Q2xsNE95b1A0Rmx5d3Z2WmNwWDNHd3cKLS0tIFpmR2hyUTh5aFdXenAzbjBtRkV0
            a1ArKzE4d2dCUmptM3oxa3NaSlFKN3cKPGAHonIp57SEvV8CjYaVgEQjP0m3gFjE
            ZLRvSePN1HMqlVygFQwvAjsXC72n6F2mDJtv5pgCppjBUUCystwSTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T20:49:27Z"
    mac: ENC[AES256_GCM,data:SV14OCpxJZKVm29Dbo95haU9JnsVbY0E2Q0PSLtVxQ/mhZVuDPcae8Dr9q+IWhu1PMsrK45mOmELic6djTpPUTeu3O0s8KfgXEVvT3DSHm3iFME0H934Yj85W/2oPxOgVhA3WDDL6LTNSEaogyNrXEjif27q4M73rSDnpAJCmA8=,iv:xgxO7O0wPrYSJb7WtDu9eLkxUIdR7sbl6cd0mJDN/PE=,tag:EDt6qn7tT84WZMO2Y+8Eow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 
