apiVersion: v1
kind: Secret
metadata:
    name: vikunja-config-secret
    namespace: vikunja
    labels:
        app: vikunja
stringData:
    config.yml: |-
        auth:
          openid:
            enabled: true
            providers:
              # The name of the provider as it will appear in the frontend.
              - name: "Authprovider Label e.g Authentik or F9"
                # The auth url to send users to if they want to authenticate using OpenID Connect.
                authurl: "Retrieve from Authentik"
                # The oidc logouturl that users will be redirected to on logout.
                # Leave empty or delete key, if you do not want to be redirected.
                logouturl: "Retrieve from Authentik"
                # The client ID used to authenticate Vikunja at the OpenID Connect provider.
                clientid: "Retrieve from Authentik"
                # The client secret used to authenticate Vikunja at the OpenID Connect provider.
                clientsecret: "Retrieve from Authentik"
