apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vikunja
resources:
  - namespace.yaml
  - pvc.yaml
  - config-secret.enc.yaml
  - secret.enc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml