apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    volumeHandle: ntfy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
  namespace: ntfy
spec:
  storageClassName: longhorn-static
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  volumeName: ntfy