kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homepage
stringData:
    HOMEPAGE_VAR_OPENWRT_URL: ENC[AES256_GCM,data:1t4GRpsBlETmwCdHQlDBD60K,iv:NKZp6ASOsRZXfJ6+bpOkGLo4HFDE0c41bFmO2IcRERk=,tag:cGfgFxdYclgnJzvqWWHg8g==,type:str]
    HOMEPAGE_VAR_OPENWRT_USERNAME: ENC[AES256_GCM,data:mxhYCPiv7Qk=,iv:0ow8bM3G1SvcYEn0Iors/1pseVuqD3F6OfZmOUnFdV0=,tag:cnw8DcBmKRzTNXrU4qsIXA==,type:str]
    HOMEPAGE_VAR_OPENWRT_PASSWORD: ENC[AES256_GCM,data:rYncThMwJRE=,iv:hPREvngsxy7yokvDUkzhO/lE2F65BN2kcme0sd72Kxk=,tag:q9tI5IYLBkjdNWBL/ZozPw==,type:str]
    HOMEPAGE_VAR_ADGUARD_URL: ENC[AES256_GCM,data:S/YFfOIstUqe+myq5hqbkxvC0/bArhQ=,iv:HHsgivx1vBPdCiDxldHBYXZ6lemsqJY1A+7RB7frwf8=,tag:5dAFQMA2Bg+A2ghrZOGd+g==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:RcL2A1s=,iv:CaKNuOKhuhtyMUctEXZKxkOf1ENG2KcdC5uaogYT71w=,tag:K+s14OWgaJOwWhgFY83r6Q==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:ClaxQkdtUNQ=,iv:UFOb6r9EEDkiGhv0g0tdKtIIrVgLsNmHE5PysnPxd5E=,tag:k7EG3Z3FFQSDr2K4QctC8Q==,type:str]
    HOMEPAGE_VAR_ADGUARD_HREF: ENC[AES256_GCM,data:S5wmnCBudA8NG/Y33v8O8NJo/c5RQWw=,iv:j9V0s1ITcdbPWw+dETSloYo1PnkgGbPdwQCjHQ56xtk=,tag:HY52Z1odI0aVV6ioXRzNIg==,type:str]
    HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:9B1ohxWMtDHQb91SEXa22NyqAnEI0Q==,iv:lMH+IVWwT4AioNMadtxOshSp9h8Oa74oOLt7thuS0gY=,tag:0l2fUKPDEbP9UO4nv/W1aQ==,type:str]
    HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:qFMbCvJnuZZOxTi0vyv4NSzOsvXBXw==,iv:w+KbOv83Zc/ZiYdpQY7FLA5KqxSbCEOX/tYbVPhRLkQ=,tag:kL6JMXHZZ2priim2y/LoxQ==,type:str]
    HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:73L5uWnWpoBpJJ/pyoV/8zP3Y6Jmbw==,iv:knhSXB9XHwm231uUGQaJR5DwSqd0eF3tqL6gCIPyRkk=,tag:reF3XTRz1YiGrmm5Egza5A==,type:str]
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:BX64bVlk87tsONjB93lIUA==,iv:whZtMFxVFAug+eMmTN/vHkrLahDn0MTSY7/UP0KOtYU=,tag:H2LdMMe05UGCsXvBWUuK1g==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:P3YXRrVJQz7PaO113Jo1tU7ZT0HKVv+zs5F1g/STb0EtBo09,iv:q5gm9s6AAfNoiambn2hx+7L2EqILrySrPPL7c6SIDZw=,tag:PIA6BIjQQXH7+9eRHC4irA==,type:str]
    HOMEPAGE_VAR_DELUGE_URL: ENC[AES256_GCM,data:b3JPDWxaaE+NaVhEv5JpyThIbQyk0HU=,iv:B2r41AgQ1N7QgfgC5LU9FzpKvRCqx6QyK9WeZvtdFgU=,tag:FbC29iU88GyvKDGlJKW6jQ==,type:str]
    HOMEPAGE_VAR_DELUGE_PASSWORD: ""
    HOMEPAGE_VAR_DELUGE_HREF: ENC[AES256_GCM,data:KMsxOrkAu8644mDHzx73SdBtGvIus3Cj,iv:oorlyJ6E8iwJyCpx7HVB5gkqAEHBiOMVbJxdsS39/FQ=,tag:mtq8loz9fLH3CjWXgM0FIw==,type:str]
    HOMEPAGE_VAR_SABNZBD_URL: ENC[AES256_GCM,data:TR2RrvF8d+2BJbrqp4G1AhKO/zKtUnw=,iv:wBahV/QYojYhivVBeH/C99IkdfPfIwjDLYzaFCs1/6Q=,tag:zLSAdd+uvFKJ6W6hXknEuw==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:7VYBa3pg7Of6SCI2vFwwcyK3M8yZVC9uI8SVMjNInWA=,iv:khGzdxxv4KUnVsiORTPMAUnYFaxsVatSJXF0P5hWpWc=,tag:ELDBYsCnQSDecS4qJhP+IA==,type:str]
    HOMEPAGE_VAR_SABNZBD_HREF: ENC[AES256_GCM,data:DDILcZAwo4bvYULMa2PnSqFK6Hmb6zA=,iv:5O0cUxFua3V1irF1hd2XgMrT5Lu9egaIv47Tpy50Zzg=,tag:W9y2g0yNT0oHte3y1vemIA==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_URL: ENC[AES256_GCM,data:e2u5VxVKlt5DUiotxVAjc5hyUwbpuEo=,iv:kz13C+E1f/iggZf3gEA/jwQGFpKlyCyIA8r68Sirip8=,tag:4cpFrnBfUX7kMK9LpbxvHg==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:LGW8OM4jhUdK4MatYib74aRzaPRbFASKEoMuL2LCGkNKFpNerYvmVi0qKdDEwp37qA4HpNUzasRSAOktMZz4Ocj7xD1toB+z7H9lstIRQqkGwnrWlGEtJb2bjLiKQk4LPHm/YSqOzSACU9Pw1rvrNxUzGdx6TsNFVCJ7FKtQlcqEGSE4VEXC1lNSfDeOZ4l+HsZ4Qp6nRS01AZ0n9HRAH94YzQmsBw6JWETJTkcotGkkX8MvMi9i,iv:knIywFQ4Cv/FVx1VaVLzOWpYwz/S1OimUFIpSxScBzc=,tag:9Fz5HYA6giB1zcrKBtnMKg==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_HREF: ENC[AES256_GCM,data:91723/O6ZEAq3kH1J+KyPIlJMms=,iv:e31w08GdY599ow47/wgl88r0510ca1bwyVk313SbXmo=,tag:fVUu6yJT4MUcnGcxy5YOhQ==,type:str]
    HOMEPAGE_VAR_FRIGATE_URL: ENC[AES256_GCM,data:s6mGfIiWZS9T93GCFUKaII51rbPFL7A=,iv:2AzoYrkv7gjp9SQ4+QSiwgVAyp4KF7HG9mZxi8S+A/I=,tag:zH3hY2P9/ISdrvTGU3tBIQ==,type:str]
    HOMEPAGE_VAR_FRIGATE_KEY: ""
    HOMEPAGE_VAR_FRIGATE_HREF: ENC[AES256_GCM,data:aFG0pecWB5zArGmtoG5xWYgaofI=,iv:MPa40WqEzt4vlSqJ/Wqwnmb6GuhO27Gs5irW9AdlYaM=,tag:+o88WL2INR43U4mTD7rHfA==,type:str]
    HOMEPAGE_VAR_SONARR_URL: ENC[AES256_GCM,data:tiQf78CNZYl4OFihyzQ5KYxGZ3GMLw0=,iv:D7S+A0anTQlACdCgqKAxuecgPUTKCWygl1Z99fccAkc=,tag:+IMGzdhi9p+yfTF/dNqcXQ==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:IsYKNfCoHusAd5jWMzdKH+SC6TcRfuIR/ChV5DJPG30=,iv:rAAmKUBrQ6clbX9JrDPPOOMMval8AU+uVGXw1nG1CgY=,tag:RmIYYLlf0n7efiuldvAYEw==,type:str]
    HOMEPAGE_VAR_SONARR_HREF: ENC[AES256_GCM,data:RdVHtyF1bLx6/Wmsfd+Ye7BcykQ3hw==,iv:OTIaAZpF4XLz7dEe52rYtcvjJGw6fXwdVWkibOaCCUM=,tag:d5h0RlYgQN2Gi4JWfgd8GQ==,type:str]
    HOMEPAGE_VAR_RADARR_URL: ENC[AES256_GCM,data:sOeDPM9FWfzPCnPrSHPATHx2dltnjrE=,iv:teRP2sCDfZrF10WiHkESUYsLPOxJYE20Crv/7RAeWlw=,tag:0LOppYlzqW0LnUSHPzj+5g==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:76BaMQPsvYD9RZkN0Ou7dW4WddiV0nA6+1Y46t0bQF8=,iv:j7ZWeSON+y71e7AOk4jBFGPleGrHlSKNA8LO1cJ3FsI=,tag:riYeYFS1pbrlD9aT9vRAEQ==,type:str]
    HOMEPAGE_VAR_RADARR_HREF: ENC[AES256_GCM,data:CefRZEDo1fN5quo3R0Jti2PIPucePg==,iv:eWSEmOuNG06X9fQpBV7zuhCVcIvdcvkAM37jhdZDRqU=,tag:c+5x2SLDjBkt7MUDQciE8A==,type:str]
    HOMEPAGE_VAR_PROWLARR_URL: ENC[AES256_GCM,data:6A0J8xPXo3+SPlZFQAWS3ACBeB0w3W4=,iv:WkbmJsA0cNLVA5BNdoOlHdhWQ/RAhLp0c4JMAtkaAdk=,tag:W6Hot/u1DtfOuny/Pp27pQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:CBhTvaDVYP1vl6ayqsbyp9ytiXdy66HDRnKTpILNWno=,iv:HCOewB3FPVusmXRjrYvOt3EkG3lXlb86PwUn1glBIKA=,tag:sPRChne7Rw3RwSefsqThfw==,type:str]
    HOMEPAGE_VAR_PROWLARR_HREF: ENC[AES256_GCM,data:8y+zJ3ccaUavsi6huydJr6Hjr08tfS1E,iv:nNRp5pmSZH80VtymdAcIYlEcHFIW2Z0pid1it7k5Hac=,tag:NE/Wc6SRCllWLSCo0dMC7g==,type:str]
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:6YiHB60lvPzW5OPnOKCVWBwLI8UCjN/O,iv:NgZ2YlfckW+G2i54CK9GQduV826V4Dl/wRUc2dvo3fA=,tag:u2p7v05XlGYtYJl2IlU/vA==,type:str]
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:j+YbzUHY6LBqzcjiiG3+tELZBRU=,iv:ViCBlWBijFCkqPTv6ccPD/zi/7dTZNDyaM7irDaeTQ4=,tag:y7icB/SCfAT65dudXIpmzQ==,type:str]
    HOMEPAGE_VAR_PLEX_HREF: ENC[AES256_GCM,data:MV1re9Gcy2k7Siys3/9BdQY9eYU=,iv:wWhsuGP7OtthVa+4VTNxFEJmh5O2zzsH/TUDshispsY=,tag:Z9p0L3N1my7KPWLTixoxPg==,type:str]
    HOMEPAGE_VAR_JELLYFIN_URL: ENC[AES256_GCM,data:8CRwgeQ6h/htQVt/Nv26Q+0Le6eQlyE=,iv:aCZf4gZ3Su41be6Oas7ECfLTkGDFvkaCS9lUVJTPRgY=,tag:MT9QKiT5OgEcBrqgZzi1cA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:rD6Dbqw03EMYuTXQTIdUsiwrLwzrfJ3iOwOGcFZbd5s=,iv:v88xIccq6ZYJUH1ypdoxZOc9j+NtCPH8uuGf/pMHEdY=,tag:j7Vl0rqtiA8sW9piJ5UoiQ==,type:str]
    HOMEPAGE_VAR_JELLYFIN_HREF: ENC[AES256_GCM,data:Lfj85Jj9dhKg2S7M8zwvcCvKTcSmlgJK,iv:gnia8KjVN3Ya+P4mTVlQKD70oKx4xXtT7CZA4XV2Y80=,tag:PEE08fDI9qtJb74SlOVATA==,type:str]
    HOMEPAGE_VAR_IMMICH_URL: ENC[AES256_GCM,data:ZNMOGmUnolo4TFQgOSgFSM44gYURcpA=,iv:yiJnJCbs33xC8RLNeSdzNoB+9VQ4FqD7mNNkwNxlpas=,tag:vcSQGE2UXhBxE0rhuTiG9A==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:hQU5nO/F3ZNITjtGqNY/VN4XeDIjch5B6b2XEj5lxvlIMkmM2ECVvKk9,iv:jtoIY8HReXT2JRLexcvqwciLfSkDAlhawHepBkTqXy8=,tag:XtEPo1RT8ENVBZKTHGrBVA==,type:str]
    HOMEPAGE_VAR_IMMICH_HREF: ENC[AES256_GCM,data:p8OHdQeFZtTPq1Wv+Ok2ZRKI1LwyzQ==,iv:/bWU7KT00gMBVYHgB91P08fDSYI+Ha0K/eakNEvUi48=,tag:Z+3kBW0BRbu3H6Mulmz/Pg==,type:str]
    HOMEPAGE_VAR_LOGO: ENC[AES256_GCM,data:cs/Wl6tYNC3M6b1svKR9TL7Pt7W+MwlEffaVvjOq0g==,iv:rG8iyFSzZJH2kugJom7eO9qebHHzLudRYmwhbTlOjIk=,tag:c1kCNED3fAg4brk5/aSrQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ1Rmc3g1eU1XTEJyNGtG
            aTdMQ0dTQ2QydTVGZjhGcHdjWmxhMDNMbWs0CkUwQVRNd1NzY2JnblpFVHVJV2ZF
            clFlM3JQRU9JZU45dkFYTkhWN3VXajAKLS0tIGJ2RHJPWkxYUnp6bnhDcEMzZGVv
            ckRmajhjNjhkYkZSOU8vemw2UVhEM3cKJjNQ6S0/Hlw0MQtpKS9CAa0c0yr4S0wR
            6MeOpBCTIDqvW7U0EmpVD9XeJXeIdN6kGTvZh5f1RNs4XA8BMU1xIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T20:49:26Z"
    mac: ENC[AES256_GCM,data:/KZ+XTtHJO9HZVYszn2oeIBq684rq1rlghKGaLCfrvGRdIkziUGKxEntbOCQPy0oDom8ZPzfzPBdy0V4hTRGx0Gcsd/4gitqT6qoYdFNndMdpG9MzFujqvXcFxpG73KOg5s37lPrU+UWwC7CgOwtZPuQK9vCsSZFOKEuSxKTRLY=,iv:+HZwvjrXnHlTufLvvkFSa1bpBDSODePLlngp7MDWpiU=,tag:ECvaFA9sX3Q8AGQAbMuiTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 
