kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: dbbackup-secret
    namespace: backup
stringData:
    DEFAULT_S3_KEY_SECRET: "S3 Key"
    MAIL_FROM: admin@domain.tld
    MAIL_TO: email@gmail.com
    DB01_PASS: "MySQL Password"
    DB02_PASS: "Postgres Password"
