---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  namespace: mariadb 
spec:
  ports:
    - name: "phpmyadmin"
      port: 80
      targetPort: 80
  selector:
    app: phpmyadmin