---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authentik-server
    app.kubernetes.io/instance: authentik-server
    app.kubernetes.io/name: authentik-server
  name: authentik-server
  namespace: authentik
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
        app.kubernetes.io/name: authentik-server
    spec:
      nodeSelector:
        worker: "true"
      containers:
        - args:
            - server
          envFrom:
            - secretRef:
                name: authentik-secret
          env:
            - name: AUTHENTIK_ERROR_REPORTING__ENABLED
              value: "false"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: postgresql.postgresql
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__USER
              value: authentik
            - name: AUTHENTIK_REDIS__HOST
              value: redis.redis
            - name: TZ
              value: Europe/London
          image: ghcr.io/goauthentik/server:latest
          name: authentik-server
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /backups
              name: config
              subPath: backups
            - mountPath: /media
              name: config
              subPath: media
            - mountPath: /certs
              name: config
              subPath: certs
            - mountPath: /templates
              name: config
              subPath: templates
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: authentik