apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotify
  namespace: gotify
spec:
  interval: 30m
  chart:
    spec:
      chart: gotify
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: gotify
        namespace: gotify
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: gotify-secret
      valuesKey: databaseConnection
      targetPath: server.databaseConnection
  values:
    server:
      # -- select database kind (sqlite3, mysql, postgres)
      databaseDialect: postgres
      # -- set connection string for mysql (gotify:secret@/gotifydb?charset=utf8&parseTime=True&loc=Local) or postgresql (host=localhost port=3306 user=gotify dbname=gotify password=secret)
      # databaseConnection: ""
      # -- default user
      defaultUserName: admin
      # -- default user password
      defaultUserPassword: admin # gotify internal default password
      # -- server timezone
      timezone: Europe/London

    # service:
    #   type: ClusterIP
    #   port: 80