apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qJB2pMZ+/yXHWg+9QBXkviTCgfheWw9Y4Oavlh1praVM5CCTZNGdShrpUiPBOGbPfUBGN3RIid+oto5b2Go8rVOYoZGvM1NMc4m0V3Dr9yi946pqlV0IgHkNJtLo01EHs4GW8YeJhy72pwKUB9wM0xlRymR9H30G5PSN8UHdGPZt35hbR4dVuqq7j3nyvA==,iv:p17vZcxMvezsnmu2gl4jIZSL4imOg5i48ANp+K/JSPk=,tag:EU+C7Lk1+k2wM12ZMJrJ2w==,type:comment]
    cloudflare-token: ENC[AES256_GCM,data:HJNFzJw6Arcf7PT9skqg13X1RlwCis/qlfymXJcM9aS/Itus5sUONQ==,iv:lw2C4cxClI0Tu3SyF7DTiqx3IqLQ889Gicnyr4JM0R8=,tag:lsDNkCjXzWsyA2nVGpv8kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV2k1MnR3Y3NnQkhmZlhT
            RlhlblVCVGI4Q0QveUg5bXFvZWRKd2FvbXlrCnJueloxcWFJVnoyY1A0NUFWbjlD
            Qzk0V1k5ZWQyOTEwZHhiRlljeVJiTzgKLS0tIGthT1VLL1d5aGVjMkk4azlBRmMv
            Snd5aDJIaVFlRG93Sm4ybkQxckV4ZmsKs3zPbDQLTGm4KoAlK/ddp7mvjc5SGzY8
            hN9hLWGSFmOX5yc3+6J5qDISxeh3TxZ174jo92UT+FzGf02h08D4BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T20:49:28Z"
    mac: ENC[AES256_GCM,data:Up7bT03DTJd4uNKw9h6CS7Pfave+QBkEmBQ2osMJ3XbFerCzrWs3Hc64PW2Z4hhgYwMy4KyWvW+rfT1UVdzrP96ZFxY+bckZiPrVK+Q1reIW/VBkT907b27FUascZ0r+WYZpG99YwjEfsch0YCzHuxK40I7efn5q9kesajLnP4Q=,iv:eSxUUjUIwRm5M6d9HshMyYCv+ZDXatPZMV60T7Ykipo=,tag:YOxMz9EdzD74IOUUrqxI8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 
