apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: flux-system
stringData:
  address: https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type: Opaque