apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - config.yaml
  - deployment.yaml
  - secret.enc.yaml
  - service.yaml
  - ingress.yaml