kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homepage
stringData:
    HOMEPAGE_VAR_OPENWRT_URL: ENC[AES256_GCM,data:0EXX+yatwjWJR/KMglFfcZ/G,iv:KPLp9yB0aFIwNw/22jONMTo9BMqHAAxN0s9WNHDgJxU=,tag:CwGj1RAFttfLJOQLBzCrVg==,type:str]
    HOMEPAGE_VAR_OPENWRT_USERNAME: ENC[AES256_GCM,data:rtPwwgl7Pdk=,iv:rghge1D+MXIbt/3SoW/JvFE5+gH6TeQ/B6aIzwM9kq4=,tag:KrQJLsvlJmdJm9wFZxtARg==,type:str]
    HOMEPAGE_VAR_OPENWRT_PASSWORD: ENC[AES256_GCM,data:VgHsl7nULbw=,iv:roBli+A8vttxVcpwvpk0acsdjJ37Qm650dQFYxmJ+vA=,tag:TDChaE1rkWyZU9svgu+I9g==,type:str]
    HOMEPAGE_VAR_ADGUARD_URL: ENC[AES256_GCM,data:JRwsLWi1vM23gWzTXvlwDWKUtjkl4aQ=,iv:ysttonssh1egoaIPoRdjQ2Am2M66IEZwUS3GqOkgJ/Y=,tag:3JMYPhY87WjiGtdZRkXhqQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:ijBWQic=,iv:teD+y9XwH5a/LZ2Ki/xUmrg+7c7yZmP5rGJYxYL9bng=,tag:JLBMpJ+zEeRpRgXJ0nyu9g==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:y5OVnPCiQSY=,iv:0Uqex2CDDDbLo/kEJZpjL+U7P5FIubTSjJW9V3whJZA=,tag:TZTYIVaYPdczEwYmAY5/kw==,type:str]
    HOMEPAGE_VAR_ADGUARD_HREF: ENC[AES256_GCM,data:mT/pTiTgbdQDRdI64ZaXB3xqzDwS7Dk=,iv:3waGdM6AS18q04m/5oN2mMB+O007U0B+gFfZ5NZWW4U=,tag:i9OsnLD/7Umj5/hoR/tHmQ==,type:str]
    HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:2nCqRM/z+lKnzCQm28Wl3eYRZ5z5Dw==,iv:cNC19jdzA8fruEznJxCFNeqbnF0ZToCfkbR5cPXF9Lo=,tag:b6lQRmhkZjlMmdNkxxz+LQ==,type:str]
    HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:3aHgJZxtVhyoieNGOwRlNr5lgN787g==,iv:/CwteAaD5+V/prdFdVKf842/weisufZBjbEzVXUwJ1U=,tag:LIH0Z5nbMiQjqKZy386qMA==,type:str]
    HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:ALrTS5kvO4VeD6zKeUnyVp8RUJ12iA==,iv:v3xHPEZMjplV/YqBT5UL1UQgyH/ueUYdIOJDnxZbL/A=,tag:viHknEpbMUQ7lIqd94cDgg==,type:str]
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:zHTN4lJwDV4//hyGPpAWPg==,iv:N4EOThU5/WI/NZkAU+jHg42GxKHN9/Mu25CQpaOJlsg=,tag:l6KOkNQxWtj+alqJp0gfjA==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:d7gWFOEBPrGko4Wdxvqp/Uo5P7Z+6PlwA/rdxx30wVfMmhU0,iv:PLVm95TbwjtqgWCBBQyI+G8XmIo6hpGppQVaOkcY8vc=,tag:HCYPGPKzxsPFHGEimZvAHw==,type:str]
    HOMEPAGE_VAR_DELUGE_URL: ENC[AES256_GCM,data:Ws9l/JXGGIza9epj0ZVR7gpCtmMnZK8=,iv:zYv2iujymVFhBWYmZKX/94Rcmk8pOT2VQahCgYhdWvQ=,tag:TcBNuB0+zQ9DysXDBe0LeQ==,type:str]
    HOMEPAGE_VAR_DELUGE_PASSWORD: ""
    HOMEPAGE_VAR_DELUGE_HREF: ENC[AES256_GCM,data:S5fe9ujpnHmKfimDB8lay1yeHfp4eQ5Z,iv:605yZ5bgUr1IA1qouPtZytwU/aZPUUOCGt7nSj+bvk0=,tag:VaCd1zeqvg5F0LW77m6G7g==,type:str]
    HOMEPAGE_VAR_SABNZBD_URL: ENC[AES256_GCM,data:lA17mLW4R9/vLQHhBP8fsrGgruPNUvs=,iv:qfbCWonCxwquJpjfHBAeVm8DHm20hHJWeiNRBfGBJp8=,tag:++yMtcXjNX/7cbGTc4NeVg==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:7ZDqQZ9S0KoMlERhmrC/jlEb0YGB8rmqOD1Fmy+iVjA=,iv:1RboFuloKQerY6e7g4F13ka0AyUnd6t1wHvhl8R5NX4=,tag:UBUn+BnJBgYVIllBSq48dQ==,type:str]
    HOMEPAGE_VAR_SABNZBD_HREF: ENC[AES256_GCM,data:ls8JJMbZQZKFjtoUEer8Ho2gW5oF44I=,iv:90nUleOVvVa5zlUvoRKM/mc5BSRiLiQOtzSox+ygzgo=,tag:Ryxag4n5/KJ4dmCdPuRjjw==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_URL: ENC[AES256_GCM,data:HtuEWlAWlDw/7Bx6ZEhabAVk/LhDZ+M=,iv:p/QZhXROjNMQeAQruWTUk0mgJSNheLom+30lLb7eRO0=,tag:FecnvZ9kb783MRJWUMJVrw==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:lbVW71TVE0Ub8xML2QvyCUb1YFr+ZhYkUQz2ZjEDpSZUUY2HS03d6BFbjxT2SbDSvw4Nsf8V8jb4tRuM1pzTuGwUnMCdDMmoV+BwaGASVYBAJAY6cf2LRAJcpqC3sGI329Q2pntxUo6EWWu78381/0cy59MOOuTn7baQMkyX8wydX9Ax2ZxPEtN0tbelGks+EFoQ4d3e4bLVhbaR0JciRDOi6ACRxZfxMYK/9p5LOGUivYSMVIpL,iv:bMqO3bfhkY0I1Q7uf4JgrBY66/Eq5BMG5RHFMZS+7xo=,tag:BgjSuiS+R2NX8O/I1vwRrQ==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_HREF: ENC[AES256_GCM,data:soAspXgDJgQBgjmmI5ZQ+J0yTbI=,iv:A6yAVf9ahOPE4hC6VZ2ze5+Skpn36lCJ0takYldouz4=,tag:D0Bu40+p1iQ/kSB4auda8w==,type:str]
    HOMEPAGE_VAR_FRIGATE_URL: ENC[AES256_GCM,data:X9F/ZueSgMTv+KhZrfOPmPER8ETFSMA=,iv:i87aKgYN3HSD0enBnUNtW7gqJJU58Nv/oHy2Uj/KEjc=,tag:0tWU+8clkGoU3G8q+FsRTA==,type:str]
    HOMEPAGE_VAR_FRIGATE_KEY: ""
    HOMEPAGE_VAR_FRIGATE_HREF: ENC[AES256_GCM,data:thh81Hqe7/SXV0X00QMpYZrSvHE=,iv:rfwngu/zm0E5Bl6CatAysz1rVV37NWVM7SKP/j95ccE=,tag:0svDnu2Siy5zmve0hj608Q==,type:str]
    HOMEPAGE_VAR_SONARR_URL: ENC[AES256_GCM,data:EkmQNRZZb0Rd2Vn4WgkwA52P4hVGfDY=,iv:qDripOOxP+9cQQ7Ix63DChhjJQO1Iil7hE5e3q3Otnc=,tag:EWBFG9wCGN7lBnEn8z99qQ==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:Da6wNXxjej+7W9sCpSn4YJH2UXpON1m3HzvkKziR3qc=,iv:1ATi49UnBBRW1mHjFrO7mAY6E8bmO6IrMIan/N1YI5c=,tag:zUZbKEIBKHZ80LmuHIyczg==,type:str]
    HOMEPAGE_VAR_SONARR_HREF: ENC[AES256_GCM,data:Yg/PFIQkuVUGdrJFQaPLOCMjRZ9rkQ==,iv:EvK7u4YXJIXIdx06PnsXwUNSP+5XW+NRFd4U8klqQxg=,tag:ZRP8fbDBoir1U01mrvjfxw==,type:str]
    HOMEPAGE_VAR_RADARR_URL: ENC[AES256_GCM,data:olX8CVEY0tdr9VxG7gyiP9Dv+CJPe2o=,iv:4aX0zyxD0lLzBqg3TDymBYZrGDKfd3H0i3RwFtfAXcg=,tag:xw9T1C4gZpVgjun4JJ6i7w==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:pUlfSrvP4/4byHDz+1n3XclAzm2ZEFKuOz/Bl0NQbXE=,iv:1RT/i9HtdJ/pNmw7dJfGwBdJbEf1V79lxGpkJ8M73UE=,tag:yHXzjJDvtp3W3kqQAFkutw==,type:str]
    HOMEPAGE_VAR_RADARR_HREF: ENC[AES256_GCM,data:9HWgcB2+j0ZobAMBjW4EK/RkCnLM+w==,iv:W9Qb7WWUFTJ0SkYItpNjw34KetTO+SWXde1vtqMck4M=,tag:ss73gk2nxJc3PyLtVQAGEA==,type:str]
    HOMEPAGE_VAR_PROWLARR_URL: ENC[AES256_GCM,data:0o8k9HKwVMT5vWhPw3BIfIztOvsrQZE=,iv:u8vCJNAxc8m2WD93QZR1NnRI+L5SxRiEqJcH7EeL17I=,tag:vnrGtcffeQJJBkVDdTQetQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:PxZLbC5JlkLCgnK4rtZnySSmYDL6R6b3WJ8eal+joHE=,iv:3xXdF/rpFpCg5cURhrxkkqqFx3sEuRSWtT+/tDF8NSw=,tag:ebVJAMJiR3x39kVD7i1kTg==,type:str]
    HOMEPAGE_VAR_PROWLARR_HREF: ENC[AES256_GCM,data:E8e7KuJaMec2vB7pcdCs+Nq4NsMYpZ7G,iv:VNFkreMC8i8Keqm1CIhLftNSS4tJuGCUhQqFhjK+tbY=,tag:Sowmk/e8cADl/p3QTeYvlQ==,type:str]
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:6YlVfiFl7KGIbOJR7y5DH8JYkWnoTVK9,iv:47yDnnwp57CZlcAPKGXRb9Q9DVGNLnKnOI+WtFcfO7s=,tag:JclzyzU5RLAYLQ3AcBrmLQ==,type:str]
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:6Af+FI7Jd3nF8rycU/lvS22EKPs=,iv:xOHpkvE0UzCgqk3Up6oFo53rJESJUiso3fie7YhkzY0=,tag:V45FTClVGdqr9EYTCewnvg==,type:str]
    HOMEPAGE_VAR_PLEX_HREF: ENC[AES256_GCM,data:rZ7a2eyKtS5NszLiEib9tFECchI=,iv:f++sj5SWC0raqj6OgvTdgyhWCqac6cYpimbJiMImXe8=,tag:uLKsh+TETgRtBSHW1f9eLQ==,type:str]
    HOMEPAGE_VAR_JELLYFIN_URL: ENC[AES256_GCM,data:P4zetzCKyQBnnxUuuwueoVOGPIkKJE4=,iv:JinXxPuz3cxeqHjYDOifllPZ8lHOuYXGP8ABC7HizY4=,tag:SgT1E3c7QwVG8b8vfk1y4Q==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:GwiSPG8zoIRedXR+o4EC+3kNgMUpYCGkesDcroM8bi0=,iv:W7hVPcN3NO6F1ttBbJGHpfYL5I6bF3OnJ+f0LJ5C8mg=,tag:H3nA7dWTYkAD87tjBQvrag==,type:str]
    HOMEPAGE_VAR_JELLYFIN_HREF: ENC[AES256_GCM,data:hBw9JTyyoeeyOHjJrTGpttAKc/NXD5qE,iv:hk2z1yp5twW0HwX2IYC61FY1mGfbck2OOE7etTqpwhE=,tag:EPOszHZBf8XYvAOpAxF74g==,type:str]
    HOMEPAGE_VAR_IMMICH_URL: ENC[AES256_GCM,data:/8g1OPMGzO9tCZQXR3FQ6pLENZJud1w=,iv:gem0l8DoT+w+rfJZlcjggVyVKjcLVOd4n88K37NlrLk=,tag:xk4w/Pbqac7EGgeE2HvQSA==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:vM9EBDLpEVM7M2R2atPJE4YlqDegQStYSQ7dFCEhxTQvOKnL++sbM0mU,iv:vvblfQk/CACn40iz5ZvUrUiQ71zWPR6pXJ2pc88gD6U=,tag:w/QGTCSNyYAIrpxr4S4L3w==,type:str]
    HOMEPAGE_VAR_IMMICH_HREF: ENC[AES256_GCM,data:+cYHalrPARPd92PtZezRlHtWTpmcMQ==,iv:c8IouSpFWwtKlAk0sV8yLLDfl+ANzbX5W2RPkwbKrZ8=,tag:9DCndggmKDu7dtNDyE7CAA==,type:str]
    HOMEPAGE_VAR_LOGO: ENC[AES256_GCM,data:MbeZEpuTw2de5jGj8y+CiH6IVNTpv1J+h0iA3JL7Rw==,iv:AdPgPo6f1Tv9GVdVmppQ1VtHFPcJ0apxUUM9glOLt94=,tag:cxjB2H1PKfONHYlPXy/6xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUkM5YURNOWc0QU5EeXZN
            TFV1bnhZQ1pUNVdJOFhSekhwMlBMU2VEYzBvCkVoNlM4ckJmZlJEd1pacEwwSTIz
            Mk9TdmVVcStHMG05MDI2RWxkRFlFU1UKLS0tIEFXNlBtYnhZVjd0V0ozZDRqOVYy
            aWlmdU9kVUFlaldXbjJLcXlINXpnZHMK+rQ19s7oj8dX9PHCK33p6Ma+Gxn/q2j1
            dgfrD+9KSIJ25Tyqacr65rHWWkMLd/xZASSiHqooanUOmlcoBJr7Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T21:09:12Z"
    mac: ENC[AES256_GCM,data:PTERgqOH/zrUoXm95JtGaZk+s/yDp0yyem5lpW+OXfS5omYiCs+UQeIRYeuqrV0rXWgHL4zfmtoU1MNB1LF++mIqRho98vKKf4mTX0+jWGBMwS5vlUHC/0ytCKjKbrZGNcwyS8a5VqGSMuujt2eiF071PHp67Wslt8qkmBSZCG4=,iv:y4VuT/nWEzs6eM2ro3vcdZA2ji9jp4m3RUlmEL5dIFA=,tag:/B+448jmpbMVvqqRU/uLsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: fc04a9956372f7c7582761c9072ddd9457d716bee3fff5786d830cf54a81f482
