kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homepage
stringData:
    HOMEPAGE_VAR_OPENWRT_URL: ENC[AES256_GCM,data:dfgEztPQbWDLJomliDlyFMmx,iv:rdKPuSqqEXJXkGNjIt18dHaovfacbxuMarF0RYX/b+k=,tag:nFITDhTUeZCNfxLOkqSz0Q==,type:str]
    HOMEPAGE_VAR_OPENWRT_USERNAME: ENC[AES256_GCM,data:BKuHq5AILrQ=,iv:+61IokQf5Bijv0KesBH8lqO2HYWfn2v4r89mAZqZdb0=,tag:uu7ppidw+AyAH4ikMhOsqg==,type:str]
    HOMEPAGE_VAR_OPENWRT_PASSWORD: ENC[AES256_GCM,data:J0eBtn9y9as=,iv:2dRr28gtwKyqckSUwgWyfCWalg1iWnHsqKxMMKs1TgM=,tag:DQd04kTJ277T3CGXh0G6/A==,type:str]
    HOMEPAGE_VAR_ADGUARD_URL: ENC[AES256_GCM,data:96SOOttBJH/ITMjX/WUadlYLdAKJuz0=,iv:E3BmHDWWJeH2Fxwx56T3FEySjG1M/X0ASgQCfnrbvL4=,tag:v2yDV1J3qA5ceFa9/pE9CQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:7iHAl6I=,iv:cW+pIcPyMYUdvFhxU4Huk0/EfhSjnwi5LdTvbntMXts=,tag:NqihYAAFtIX7jnCntJ/5lA==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:1NMPExrG2e0=,iv:AlZz4nIw4zSL44YQHtRUESlgry2BOLi5zi434CEORCQ=,tag:/kbBA458h9c5HROk+Kn5fA==,type:str]
    HOMEPAGE_VAR_ADGUARD_HREF: ENC[AES256_GCM,data:mYPDqb2Y0Hwz0LfPPFH6O1ZdLkW4dV4=,iv:+2a9BE6ev1ue2aUDFZPM6206/MM+tUGjAOeuxlv7JQo=,tag:aLMNSvp403Q9Dg9+th0JSQ==,type:str]
    HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:l7yKuZw4Rhvy+meImREXR7mZgPgUgQ==,iv:8qVZHLKRPWOT/8g9cOYTPVznrZqqwmghpPDRmLKETco=,tag:Qx4EWy6r06mJIEZZhnZUdw==,type:str]
    HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:9Eq+0cIHqE1eYWX3YmGYmZKZFbOqjA==,iv:qnbz1cMJ0mrgIZGsNIOz8AnVZbUa4O+k2rRZ/3ZYm5s=,tag:Gald1yw9OW3/u02HNVIzlg==,type:str]
    HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:JGPuJCbrvfPEOUo8H3/QIiTJlRD1uA==,iv:kYirmWpEwzKc6ZbNDC+Fi4hCgk7Qu2tnDeej4Djc4tQ=,tag:KNO2bLdj0BJXHmJTx32KTQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:YscWGH/BGMHmYk29r35NNA==,iv:RgXQLmAXSRwHfJz+OJUnnI5i4lLeEwXLVux669mYVJI=,tag:+aQFDNL8qYPiN7/gamWjfQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:mPRk0nScdpdQDUyXM1OfB9zW/vcSLm3XCm00mvFrc9Rx4WAJ,iv:nZy7sJV7A6HEq+fxlNHTUtMUDZcTK8SKIoGa/ywFPw4=,tag:qASf/470XPe4HxgxmzQCzA==,type:str]
    HOMEPAGE_VAR_DELUGE_URL: ENC[AES256_GCM,data:o45ON2A6MgrJfq1F+z8lPg0kc9QaUKM=,iv:0EDjRMyeeYqATTCSf4738W4I8GRFvtFHt9UyliINnr0=,tag:TpPyaJgENYfSD6cN+WK+ag==,type:str]
    HOMEPAGE_VAR_DELUGE_PASSWORD: ""
    HOMEPAGE_VAR_DELUGE_HREF: ENC[AES256_GCM,data:CMo+QbU+MVd4f2iWZsFxaYGTyNQKzmAa,iv:asw4r732VG5Y+Tg0v3ZcFEvX7rW937QEVMRQTBEjIas=,tag:WZMYeVG3dAutg5dJ1fqNzA==,type:str]
    HOMEPAGE_VAR_SABNZBD_URL: ENC[AES256_GCM,data:oOpLKl6jjVGUUlvxiVaP3YGwy3BTWOM=,iv:nfEatwAeA0AT+4nWW6cks7SG6b8XZ1DtBWrgS3TfsOs=,tag:544SeuVPo+A1BqO5aq8DNw==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:l3rqJmC2tuXXiI88/Ov0HumMGobzJ+ZqJOvOWLeW4iM=,iv:i/W8A9CLC1/GNfE7Aj5nnD2lk1pyzet18xMYRihXNxw=,tag:Tz9dM4DqJMpPSQJI7cvI3A==,type:str]
    HOMEPAGE_VAR_SABNZBD_HREF: ENC[AES256_GCM,data:2EvPFPhH37ej7uSwsvXuxrVfLvd2f2s=,iv:a//RSPlpyrgIcnl7PPokm2Qf71yAmf3feRgjkXwk2Ug=,tag:F+e2sOluJFH5MSV7OrXLVw==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_URL: ENC[AES256_GCM,data:LOh9/bV27HaK5oX7zC8+o14LtWkVdpA=,iv:Yx+JDTNXRFconz9aaB+vwfsgGQ4v89t9WHAzj7OCiOs=,tag:3R7yCNkvp5GKeZLOnva82Q==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:/KXG+66LBVXqOfXLhxbebugE+FZd4KU9D9FBFe9qLgCFffdPw78RX/AWlfTuw+gyY+nX8sZGooOJ4cUpq+jGjSNUmPAqEH4WevNL4N7TrKcPkAfI3phPIA1W3yDeL8tWyJD7ZjOKNzacx2eKkqWStrCcPSZ8P8jTpHC+NsoVfpuSI7jhDbYcK7uQFyhkLCay4DczbBBxp3ZrasyppAUOHOur7irxXiTwUJd7hdgXFvVDuNBrhGWS,iv:uPOYZSPSpGM0siKYuhvdvt7DtTUfU8FAlx4xc4cpbE0=,tag:1o2rZkpaPnb7XwsG/x7Oow==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_HREF: ENC[AES256_GCM,data:fE9Pww3wlmgR9PU7ixdQf89+RnM=,iv:T0+VykScgwDIAIxPQPTxxYiNLgV3Y67s626Z8RkoH8A=,tag:8Z77f5HFBBtyMzP65XzMUg==,type:str]
    HOMEPAGE_VAR_FRIGATE_URL: ENC[AES256_GCM,data:6QpFEyxnADNJFdEtbmV/zb3LBBNEzDM=,iv:08V9HP1C0B5uzXTvKBPi8iPQjrTW3GqS1YDFlqPjhY8=,tag:vByMoCyeJddCb07JMzW/3A==,type:str]
    HOMEPAGE_VAR_FRIGATE_KEY: ""
    HOMEPAGE_VAR_FRIGATE_HREF: ENC[AES256_GCM,data:59Aw4ZJS2SbXb+DN1SOh+IdtNIs=,iv:hx+BoL2QFDZJfyP/qR71UKs3mogAWX/itEK7Fz/1J28=,tag:04WbY49k0IVPzKujjN75AQ==,type:str]
    HOMEPAGE_VAR_SONARR_URL: ENC[AES256_GCM,data:Bur2ZKA7XlqVeQA57GqlpsCFAlJ6ecA=,iv:ny+iEYrE1lQCdVM5cY0LKlwemdn66tpHhANfveXRfZg=,tag:xQBbDOCTLx23ULCfdNscpw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:bISP1IXJdZ0jdWHPBOkR/N58ZT3pa6WSDGAQY2uShEY=,iv:fYiSiLO48VnByE6ENI4FMf+dxUXoFcARdarMxHE355g=,tag:tX3UkBR09CMUg1w5LLivdg==,type:str]
    HOMEPAGE_VAR_SONARR_HREF: ENC[AES256_GCM,data:64wCGfZYa3p0YVHWf+Y57X4NP6hwYQ==,iv:lypbQ2xZ3e7DDNQDWSFYYPu6wXQ1uwZA7e+a0s2id5Y=,tag:cZL0FRgmKwkjPcfajpSpLg==,type:str]
    HOMEPAGE_VAR_RADARR_URL: ENC[AES256_GCM,data:l3K/cU2uLD8FJoKRHakwNOeMxTGWAXM=,iv:Dklwj98/duykBE0pLFsD5NpaA9cWpm0y5FYoCnCz1Nc=,tag:AGCIfS59MnyFmnJodEL+Xg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:B/Q2mkJd2D4x6coIz2fWYzh7Q73QZL08Kd0AuPcOttI=,iv:NL0RVlFDSi2QoWO7/mHBAdo1lr6pyps2lJ6B6J3NCBo=,tag:7kfKzJrFnXTFamKCiuT0/w==,type:str]
    HOMEPAGE_VAR_RADARR_HREF: ENC[AES256_GCM,data:z/qbqQ7QhmpOJCs1pdkLBUB8TPnJog==,iv:a2PFo0Eg4UG4kcIH0dnAX+xVEobHefFvnCLyn6MMUXI=,tag:3QRSNHhYoiFUZxD9tmNmRQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_URL: ENC[AES256_GCM,data:v61SQM6esihVJiD4CVHuOw1M1Q4ty+o=,iv:hul46L4MjjIz1MnV5M62+utRKB7p10h/0MXN/q2Fviw=,tag:RpL1FeLvbxsehE8kjPxMhA==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:l+0p6q2bhW5bq4eMgvlC5zwMzIVIDybUuNVwiXFCqDM=,iv:vvcmKQh/xR7itGLAFTe+OLl5Z51WrYvoDpJinQ+1n6Y=,tag:5ZEWo9ShUtkIVSzVa0fMcA==,type:str]
    HOMEPAGE_VAR_PROWLARR_HREF: ENC[AES256_GCM,data:knuBY4r8t609tMLvigCxTiO2DQd8IP2n,iv:tmzSqRq6Cc0XZtFvRg8n80O0sTdUQucOGur5uGEua4M=,tag:lyV/DLlODxCy4FZgfSxw1A==,type:str]
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:djrdIIh3wHUygZn8C+g850e+Pgi15Xyf,iv:DwRnVhFZFLUvGLNu5VHynZprYkq1o8u6dx3S7pjODLE=,tag:iHLDgBS/iA5ntNnQOH7qSQ==,type:str]
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:Dty+xQlirtI5hDba/rkxprizkt8=,iv:a1A1rPc4zF36IuCeBbukfmX7giFqw2YFFe0kA7F4wkQ=,tag:q2AAOZ9GaTIITFFb6MjlMg==,type:str]
    HOMEPAGE_VAR_PLEX_HREF: ENC[AES256_GCM,data:yMFFQzoTH0XzQNk2mxP3RiM4Vos=,iv:Wk0tRjymxPhxWaoFfPSjHUMsEOrgfcwEIsxY62/KfNw=,tag:EtCPnlb7BBD/dOU67NXinw==,type:str]
    HOMEPAGE_VAR_JELLYFIN_URL: ENC[AES256_GCM,data:rD6qQPIZuHIxALG1nAb0W2oojUhl3uY=,iv:XOVjgciAa+EIILMkCjjop3cv9LOVpk9RlhTTVyt3K/8=,tag:S5ZWcANUDcTHEKYtuOQPaA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:3ukks51jj3o+YXHlKdDOPmdjwiNs4/fja6FzDqZDBH0=,iv:Ls0lKkK1uGmaMz3vI7ixjDNfDylr5XeZaZklEjjJfuE=,tag:F6b97sR+GEB4Dc56OjlnFA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_HREF: ENC[AES256_GCM,data:OlCw5UJf/bLBKFlaMPZKpaWqmQIh2YRU,iv:qsO5FeI/fcrsNMoy2pH8I6avgRFDSck/1inM8HJcJco=,tag:UeHw8h2kW2d6XaxcDgv4BQ==,type:str]
    HOMEPAGE_VAR_IMMICH_URL: ENC[AES256_GCM,data:krgHRSLHzyV0sGRZh2ISR7uRgRQ0LbU=,iv:0blGb6q6c1jmgsW7KmpBujx2NpLezXXHBzZq8z08B/A=,tag:rWOwgRz+PaDZ//bUaE2o4Q==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:hmty19WjJIeWtvhn9KvTNjYYo9RrZlHoVkQ4BLt7JyIML32zIvYpOEsm,iv:c3Z2qWT5uvYrJGAQ3INiC5cYIitfXo2Sll8IuSREJy4=,tag:lzTfo9XQxpgKPpTSLiccvQ==,type:str]
    HOMEPAGE_VAR_IMMICH_HREF: ENC[AES256_GCM,data:e8Zfnfw3S8gT+NRsTOpZxWLk4bg9vg==,iv:aV2FkzEsZ6EyGE/ZdBDj2Vj5OnbTrAXsEYDUqO6QqDk=,tag:8wi7AE9FbEjJ+3yGoZkcyg==,type:str]
    HOMEPAGE_VAR_LOGO: ENC[AES256_GCM,data:H35MslooTbXRX4mkw3bRpAp7EKzJA7oTlttCJf1HSA==,iv:AqxwcfpyRvQdSRbTvbRZL7OtI84j+PrfHKeSSWzj3d0=,tag:sN12f5btGvFv/LxoVeOCbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd2J2TGlnVDF3OFRCaXI2
            aGhGcm1LdXFqQ0c5Z0NjTWxnUTA1RlMwZXcwCk1MS0RKeDZLeHR6bXV2am1BK1M1
            aTRtRmRPdGlTK3VmK1NFbEhmSDJXeHcKLS0tIGZLL0pFYzN4UnNrdjJwSWs4clB2
            Yk1lSTdsTTQ3OWs2VkhXb2Rpblc3bWMKf09e6JD7DV+t596ukdjpOjzuSu1CgOA0
            syYVoun1yhOkZwd2u/5ZQPrkehNqI80gG0EgKZvxiIzD2ioHW+DQ8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-28T19:17:24Z"
    mac: ENC[AES256_GCM,data:ArH10eZ6IkdSvXQeUA7i3uQ2YfUvmvVkwZRLpB+OaxlSa35uRq3v89qxCvBs3c9AvgBhMVtmcQjP4rPyDXG6AKkpXzaMLIflviD2YIEBY/RFobH4knTL7zzXzopeHSkxXEuiiIxR0wqdhPplz6gDekeE2A/yeNjZE3ZaZuUxMMo=,iv:8xH8YlX81CgO7t5C3IPLchHBFb4i5oMoGV3gH6q3UXE=,tag:yeD/16W6qCfI00sbV2EPRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 770347bbdbcf67e8e0f101dab0947c46c76c0b13fe81f507e29a7e405adc4673
