kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homepage
stringData:
    HOMEPAGE_VAR_OPENWRT_URL: ENC[AES256_GCM,data:NcZ6JIAvP25bT99q43VGu4wI,iv:wIwXadgv9974qNnRb80dcKNo7kZIASaGxN6Tju+JuiI=,tag:jI50wwGjLycouPPx8xWi8g==,type:str]
    HOMEPAGE_VAR_OPENWRT_USERNAME: ENC[AES256_GCM,data:uz2YCmWyDnY=,iv:rGAYCyYCsrz6O4+asVsHYu3Sz0YVG+yjOj2fhp2aTxY=,tag:+9/xC9FjkUfoBwfcshWZDg==,type:str]
    HOMEPAGE_VAR_OPENWRT_PASSWORD: ENC[AES256_GCM,data:Dh8+u/BpQC0=,iv:DXyTTShki/b1sPlM0PdwNFI9zpu/4761klo/hpa1oJY=,tag:D/rlDNab2bqzJCHvoM58wQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_URL: ENC[AES256_GCM,data:zuexBoPW43XGxjH8vA+B6Bu0xoHWiEE=,iv:8MHc6k3xgbwMjC885cDEKH7Lpul/pi3+leyyUBF4deE=,tag:DA42sEdX/BPimsJ+TcyGsw==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:6SC37BA=,iv:CInNPLyHyRoEEp9hDFG3yfJrHYTWwOmJo6T2GXir81c=,tag:tjvms8G6BjxL6RE7S8PFwA==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:o2ZZN3aQ0SU=,iv:6/gg7ZaGURML5stR5E8v+c4bQQhNpfFPwK/nO77GTt0=,tag:qPWHfh5dptmRGvSCTc+CoA==,type:str]
    HOMEPAGE_VAR_ADGUARD_HREF: ENC[AES256_GCM,data:PegX2KhUchhbyVaBoshCgHBJhhx6Xnw=,iv:neIPnfkssJthyKtD6AxAzudUTo0uiuIc7WIiaXKOwdM=,tag:Mrk+lLJum3vjq1/dXYs7VQ==,type:str]
    HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:B1bUsMniXIi2W0piT+LWQZVEwSJX5w==,iv:W1HF5fz+JMdW/A9HR3WcjdV3SanBmNMQt0irmyJRRo4=,tag:7IxD2rpnVx2kTTDph14JPw==,type:str]
    HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:1FPGskNeblHoaZ9Iiozm1hZULDcyFQ==,iv:nbyEp33WtkZ9TbsdkGSc6aD05BsVvoLOP8/Zw1rvOOg=,tag:IFKn2s3qkMaRGOaZWIZkAg==,type:str]
    HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:/bZzKnb4P+mw6R4eWakw6u8PEfPyIw==,iv:9bAXfgo28Xio9ytx+3PyBGVv5NAjhpR69PL/sZdQhVI=,tag:gzqf56wRzwOHgI+nwH5t5A==,type:str]
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:0RR1v7sSV87JCNYOGzWhQQ==,iv:ATbHm2Oto8pVLUUPAxeP30eb0wRubX/8OHiS+MmPj9s=,tag:x9Op2/7AvXUM0Gkdcf4sAg==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:BWOyQFCTg3m6NZQHcQISivGihZGlqQaccL8/Y7TApsMHRt7D,iv:ynMDfkWoH3nJOchPlgdUCL1ChzhfZMiKFw1BrPaE1u0=,tag:7oEfwpb4aWsPgitXUdO8ow==,type:str]
    HOMEPAGE_VAR_DELUGE_URL: ENC[AES256_GCM,data:sYMi1tB6mr15CXreJiAhBAJUW1uOCRQ=,iv:CT2XiOT8MnvnoXIL2zTL8hYBVPtQ8gvFuOLFNhcKG0M=,tag:jUmQMLXGgU2mxNS+jKFqOg==,type:str]
    HOMEPAGE_VAR_DELUGE_PASSWORD: ""
    HOMEPAGE_VAR_DELUGE_HREF: ENC[AES256_GCM,data:nFxRTo7FRGA9XEv/KwwfREHzYRcRdYyf,iv:TeddHajbUH2zxfoQPLAcLieiuLutVgR/06jjTRJe5QE=,tag:hNB+K/XbX7en9dsnx8JBvA==,type:str]
    HOMEPAGE_VAR_SABNZBD_URL: ENC[AES256_GCM,data:9es9mLO7skXGnWrM4uB8Wg5Nuz8g5IM=,iv:jlWW6E6h/PQD6pt+QmiccB0SM7qDZC2q/yZCH3ShlDo=,tag:Ei+JzvkWy7sMifhbNM+m3g==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:lz4pBTPaj3IHkAPl6Vb1SrvaeYV8+3iVceVNpkgseLs=,iv:OSc6xEtnTttX88jdZzpbWSqRDtcix6eYVZ/Gb7a27tE=,tag:LzBsXtb22gvLGwZ9QODb2g==,type:str]
    HOMEPAGE_VAR_SABNZBD_HREF: ENC[AES256_GCM,data:TVmSe4wRfgxoURwNAJeyhMsCugMAFos=,iv:1HuoLO/ELG/lAe9lVbkNs6otnjpy8WaInyEnPvdtSTo=,tag:0x/Y7//NW/8HjUQhwAVA8A==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_URL: ENC[AES256_GCM,data:Y1/FYIl/AhpslTc7y4aJP8Htsg0GLVw=,iv:rzxyss0zflpBap+V+AosUzCHr/09OnRi9JxTZzdSHqQ=,tag:4njUjg2XLwl+REAX2csEPw==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:qU0NsDS2HGZ5Gh7ZOTKniH6qOdMSeU4C/P/T6QL3pNAhkRS1D64r9DKjw5IQA8iwUGSz06mkhp5gGIXPUloPNGTLTevVJ3WRMgkKfXCZBKNHFRHvWkzIRNd9ukq475m4kabyu1dIRUE/kP6802EROvUIQ/h1yyx6IVktxiiYiXuAfi6k4/6b9KgSrj1tKCcJgchnWmPdMf6yyxKG0DSRjjvCJ9RO1fMd3DFKm7FG3NIF/x6gKmKO,iv:cYrboQajkXHcAYgR/7q9tGPXWcmRgbB43Zs0jzCGzuY=,tag:Y8a0monRu+ctTBYD3mp6cA==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_HREF: ENC[AES256_GCM,data:Ny3yp0mSThd2sl9wMQTspp5sWEk=,iv:BSa70OCJSjPqWqH51/2//TV8ZQi2ddJrD1LByajcONY=,tag:N+0l0UWT/K/M8jXRrYlu3Q==,type:str]
    HOMEPAGE_VAR_FRIGATE_URL: ENC[AES256_GCM,data:astxjNMp1c4hb6AOJAyWO+ugITB2xPE=,iv:Qk8EUhVGF++E9gopJnVROHJgXANZw2idtEevgu3Fnyg=,tag:AykPJ9NxLVsJshFuc7AYTQ==,type:str]
    HOMEPAGE_VAR_FRIGATE_KEY: ""
    HOMEPAGE_VAR_FRIGATE_HREF: ENC[AES256_GCM,data:EjHCw0Ut+Zed0vAisjlY6Lb6SW4=,iv:M1gf0kdSJvxHJpc4y4NeTmtAmIVUNuUWWju9j6wRcRw=,tag:6vqifSEj5+jiJrC4TIRc2A==,type:str]
    HOMEPAGE_VAR_SONARR_URL: ENC[AES256_GCM,data:W0vs7H4UqjQnbLxxWi2XoXpF9WWZG84=,iv:WQK8+noyMaCsSxx0J+u6enhc6Ca74sRkEyog9Apc5b8=,tag:ASZOk0O0NtzyW/NGb4C/sw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:46qVOz2cGP22ao7brpEVVL3IanMHWKMbp4JO9+r/CGQ=,iv:TkP137ZgbAUvkGVUX3m7XpggZ6F+UVJmPqzY4hs2nDQ=,tag:RXH2RBRFGRKfdZTcZaX0JQ==,type:str]
    HOMEPAGE_VAR_SONARR_HREF: ENC[AES256_GCM,data:gnMjYuFk6/LXM19AHJ7rUzxGUtZIHQ==,iv:4KV2bQ3+4X6PdZ5Qulz2a6wZbKDdn5hPvzvDAdgUXLw=,tag:1toe55o6aSnoN+2IB/k1wQ==,type:str]
    HOMEPAGE_VAR_RADARR_URL: ENC[AES256_GCM,data:AMyrxO9yAjPhGdhaNVnQZ7OLbv7dyhI=,iv:LKZWhziv/o+SExokECsDKvy4r7/4ZrgZQ9OWPfd+aEo=,tag:Rrwvk33hkN24j91VQ5yvmw==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:OJxw6MqmRDJd5d+ZDeQnKiWtm/cuLEL60+Bg2h+5P90=,iv:aT/+PcIg2i5g2l+RKOgdXPXuYhrbrvLIxGg3RRMYPI0=,tag:BEtZ2iyCaRyYp131JbTGUQ==,type:str]
    HOMEPAGE_VAR_RADARR_HREF: ENC[AES256_GCM,data:cvOUEB5NnVDAuctFvk+YgC+Ganv24Q==,iv:yKd0j5IrGqE9PJCF25APLlnQ0KLSzGHIqhWI1x8Iht4=,tag:Ikykr8IWPOUAUkaIMhhLlA==,type:str]
    HOMEPAGE_VAR_PROWLARR_URL: ENC[AES256_GCM,data:ogwahuTdp7XcMhCLJq6KOacme37knu4=,iv:cHL/ZOTKMV4TzCeyUcAtlbmUNmtCoZ/cv0zSqiCYyiM=,tag:ITPJFOW81AQOoi9B7chDAQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:lnlI47eMdhibvZN7r+hSdThP5OqCaVP+rLfTKp3gX3A=,iv:Y5k5j4pJldCPocMBuaD9uSMiI9UVZGBQjuolQjV0ooo=,tag:T6kzUYqXkt4x11n4ze4wNA==,type:str]
    HOMEPAGE_VAR_PROWLARR_HREF: ENC[AES256_GCM,data:YdhRfAKh46mjxzeQZNKO8R8hXhtKMtg0,iv:GVUVs9E293ioQEhsg1n2hW0F5zpjmX6/wyLnagKprHI=,tag:wUAovPRF4xIw5BrA0nsKEg==,type:str]
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:JxgIFnddrTLknwnx9Nvbvg+jTMrWo/Wh,iv:O4VPcUQff/75l9HFub5MWAJY9Y6pfDTU0FuviYrwil8=,tag:xA1yb5UZKsGAihjh/ztH/A==,type:str]
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:3TYbScuqSd2PcoIedfRfsiLyBLI=,iv:aYeTrtnJHZBnooKPUPsAhK+PjJ9bHiYQxbZt9QdzJNc=,tag:QFhlpP+dnwGj7FcGNhRCtw==,type:str]
    HOMEPAGE_VAR_PLEX_HREF: ENC[AES256_GCM,data:YyUX8HygVrz5Sdfx2KXlSVdIplU=,iv:fwS24bmRI4lj2p7wHh7UXzY0Ur/zdK+n9mUThFiAfoU=,tag:2OOxGmJkKpfScfY8As3mCA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_URL: ENC[AES256_GCM,data:rn5FM1khMzWxZeH14jnEWhveB8/wZxU=,iv:3N+2J4YyeBpsz2C23FLlb9NAzbDE+03xi0rCa7MGumM=,tag:gwnexKUC0fC8xEjFAQeYSg==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:yZsQAELP7la4SjenmoO64Ipu2E6hjEtWLGkJtEyMCGU=,iv:HiNZzpqfw9ihnF5l7j+9B8oinEPScf7y9ShOZSqxtB8=,tag:hMggT+gyTgdByfQgHU5wFg==,type:str]
    HOMEPAGE_VAR_JELLYFIN_HREF: ENC[AES256_GCM,data:4DNec0YU/J6EBtv+pi/27Xy1EBJs36U5,iv:0q0aYR4rcP0tqDuRxAPi7NUqgEJDREnANaQjBTGjU2U=,tag:wQ/r8K7wTjaMA+Iw4rSEZg==,type:str]
    HOMEPAGE_VAR_IMMICH_URL: ENC[AES256_GCM,data:oK9ifoYRAwIwgj8FvRWVImOHQTLNP4I=,iv:pUN3dnseiKp9HuJwjtqNSWT3iSLmvEIPga8lZFG1JIo=,tag:tT33de6XKi3iSmtPa/3pnQ==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:dpP3ttdDI2KUD9Lb4V/RyaHsSTJyQ0kijECPtyXRSTIJLtdzN9uPh1n0,iv:TQXiTMt0wd2sekq2IWBcvodu7ykr+Vnm1QMFPsEA4Ss=,tag:aP0LFYfigtq+M+jGzAo7Uw==,type:str]
    HOMEPAGE_VAR_IMMICH_HREF: ENC[AES256_GCM,data:ynm8NjHm9QpH8H4aV/DJIvpnfWQ8uA==,iv:sAD0zH7oCjtnGB4Yef2t1pTkdrUcNO73e2aibcSwGGU=,tag:qH3WVRx9NJSIWQEu+vfBkg==,type:str]
    HOMEPAGE_VAR_LOGO: ENC[AES256_GCM,data:McNoslfYPBUxcXwknOEL6cWaDoDaevoBfTnjlCMXjw==,iv:Q5iuY7cPvibLg2XLz2X+Fmdzgi5rGsM0JHk9kpVLFDY=,tag:ur77V6wKRNhhj4he98SKEQ==,type:str]
    HOMEPAGE_ALLOWED_HOSTS: ENC[AES256_GCM,data:ef8JHLjgow==,iv:Y0JH1Z8hslAyo1j2XwI7VbTRPVVhrpov/LekhOk5kgk=,tag:mVe7yekPEWKf9P79AD1PNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMWcySTNMaUZYTHNyUlho
            N2szb0k5MWI1L25kMHpYT3MrTmtuaTZaamlzClU5NFlyU2ZWQ1BCY3hNZFVqTmdC
            Ukl4QkVaWXhOOVhjQStQSENqczFERjQKLS0tIDRpN3MyTlRwMThrYXVDMU9seUx5
            bG1rTDFoS25Qb25oMzJUUVhpMS9qeDgK//WBh2is9hvDtzBfRM9ybYyVxoNBrUQP
            sbdExFhKAXL+NNj5iXsUkVLVDQva/RPwfiVjOIqlYJ15Sv+A0XaDwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-28T19:38:37Z"
    mac: ENC[AES256_GCM,data:pLBJfrcKU/VHJz0qa3gbsD9srMcuEwKfpG1azMsFnl2A5B9SE0qSHMq7Bq7g3itjYKFVUP5NGm4uCKp+iM09939duljlY3lRfuXkw14m2DzSU9L63PBxYvMHs/Max6yGKhYcJaYBcbBzxY2aIXlJrgjw/D9OLWqDpev7zGXNE4M=,iv:T8QZZY5ez+LTZv6cN2op7OEiavIaIcsZQqAIZwZT/pc=,tag:DAosbMoNyTc1hPOEwxFCKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 023cbc201c8d587fb46c092efe453370446ae56d12bdbca05a4d57eef7e1fdae
