apiVersion: v1
kind: Secret
metadata:
    name: debtmanager-secret
    namespace: webdev
stringData:
    APP_HOST: ENC[AES256_GCM,data:vD08FzK8XnfnR85MpTZyLnZ3IYvvIhC5i37y,iv:wlwDpMDn2yqbsaE0G0zJTV+yHqBTdufMHH5txGYcP2M=,tag:/74aORsVDk1sZfN/96o9/Q==,type:str]
    DB_PASS: ENC[AES256_GCM,data:HF3kxc33kNvaJif5XwFysg==,iv:xE/kUL8yF6DFUKzcLOk9i26zsevHdJ0vba8t0GUVoWo=,tag:awOthnZDiw3BgVhItNIOOA==,type:str]
    STARLING_WEBHOOK_SECRET: ENC[AES256_GCM,data:Jp0glfbwwS0xEINOO1EeWMR+X1pSBA86siZAMfyZVJpxq5UU3uFNXtclF8dLRqwI8wyG6Ea79AkR+C5PX0b1dp1x1fdA9uFbtds0pMDxBWqvQUd+Cr9UJbDnrweou0RRepgQhLgfld4PJw73a6MaWxl8RLn+jrtE+BddNagjaWJoWA547PXGmGrGWf7GpsJU6C8UZfIbkkI0LhatisxOvhjnFDC4rg4mbU0XqmZeUd9d6KXTKkNgzia2RIWFIBac/mbg8RP4eUCghQwfkev/KBL72/cQd4SG7obXPKSLRn+5hVTss1rYuNh+oSU3rE2R6XZX9UvP6B8bW9uRwu+944Sh7QqlfueY+fNMrYtLyku98+TCCjbOy6VSTMD9e0xnlIdyKXpC4fnRHG0+u6SAgWdLEjyIVVoRqk7CDkJ13lp61zuEnf8wEASEyrHRl19wVhU/X7K6oTEeTVVpfXc17vsGC67l3xLj6eNJmP3xG2iJk2XBnfmfpThg9gnubSiCXvGsb9hLl8o=,iv:u1h4XekfrQ6RWGJIV6E8ccDzUMuMA5ij/yhdfhHeN3k=,tag:wNVNrspSofhxUHFih38GfA==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:eROEmaO6ztBgYr1QcvvWZRwybw==,iv:1HQRUxKxMOLcjmW0cIXtv2bboHJ3pp2o+TLoHaI5gxo=,tag:qjz0JuuLv3dFVqAEID8LdA==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:wFeveQfTmEHFtoxmYzFfUtSYvPwBXqDzT22zSfmTCm4=,iv:A3zxbfdsjuIn4KJIdj0o85V0Hc71XuuBCUvXYBCwI+k=,tag:28ojpsFUPjUfmNt8/GvBTQ==,type:str]
    DISCORD_ADMIN: ENC[AES256_GCM,data:J+r5txckg+RQYe9p51pyS0cJ,iv:kUpZ4jpEQFtqlVZmHLPQYhnlCACxd3E+n0bPyGYpTLM=,tag:6GQlMfNhPP4qt5xqC2F9sg==,type:str]
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:lci8SmFydqmgqMC6pTDW1uIfB3YDHM44+h85wOXfLvluTF7/KVgvzxtz42LIeUK3zKRcIHxawlEfBdtCd5112ri/5LQWesY3yBIhyaGDd1wT55wMrpoMTEjLuJMxf9GG1aDiZM1c26OC1v4568ZTWcV5wrVyEkypmrng,iv:xCEPObrWNjLyIBTtiU5nI1uh+8HiUvfT5lFtEZ470tM=,tag:UOIO6Czk/oCe7E8R1QiWsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUlhNSVdyd3VwRTdnTXNV
            c0hMcXRBbHhPTmV2QnB5YUNndkpVa1pUUzBBCjk0cUJiZ1NQZWNKaExrTmswUFE2
            MUZNRmtRUmNlTWRPYW9OMUQyNTNXNFUKLS0tIDZHS0JVZnoxL0tDRjd4UVFpZnh5
            WENDaEVnUDN0Ynp3azM5K1daZHpBdEUKyyMgeh4p4COB6fTHCySXkcKuLTEI2c8A
            tblRp+tWZn1SLYLahPGEkJ4eAG5MO2+h9htKCQUHJ1LjJZi6Z8HB6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T20:49:27Z"
    mac: ENC[AES256_GCM,data:gbXhBwt8hXbw+4TZjHgHXhBm5OYeiimRh5rHuwvLuPn/RUdJ4GHis/UWO0ONWA0xtXR7NUx/YoRU8wQP9NwqS04wmQCpuazWxpXQfadNYs80lRT5MxXyVb8ZgQsHaEgxHw/Mh4FSTGxKesZQW5aPeXHwpm1NIuI0oO2Jso8mjXo=,iv:fFmR2qlD7fFL2XNF360EjIjVG6vS1MVzfzy+EiDQzUQ=,tag:xiexZLDSCWJvFFIq5laBJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 
