apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    volumeHandle: pgadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin
  namespace: postgresql
spec:
  storageClassName: longhorn-static
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  volumeName: pgadmin