apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 30m
  chart:
    spec:
      chart: crowdsec
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: crowdsec
      interval: 12h
  values:
    # for raw logs format: json or cri (docker|containerd)
    container_runtime: containerd
    agent:
      # Specify each pod whose logs you want to process
      acquisition:
        # The namespace where the pod is located
        - namespace: traefik
          # The pod name
          podName: traefik-*
          # as in crowdsec configuration, we need to specify the program name to find a matching parser
          program: traefik
      env:
      - name: PARSERS
        value: "crowdsecurity/cri-logs"
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"
      persistentVolume:
        # When replicas for LAPI is greater than 1, two options, persistent volumes must be disabled, or in ReadWriteMany mode
        config:
          enabled: false
          
    config:
      config.yaml.local: |
        api:
          server:
            auto_registration: # Activate if not using TLS for authentication
              enabled: true
              token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
              allowed_ranges: # /!\ Make sure to adapt to the pod IP ranges used by your cluster
                - "127.0.0.1/32"
                - "192.168.0.0/16"
                - "10.0.0.0/8"
                - "172.16.0.0/12"
        db_config:
          type:     postgresql
          user:     crowdsec
          password: ${DB_PASSWORD}
          db_name:  crowdsec
          host:     postgresql.postgresql
          port:     5432
          sslmode:  disable

    lapi:
      replicas: 3
      persistentVolume:
      # When replicas for LAPI is greater than 1, two options, persistent volumes must be disabled, or in ReadWriteMany mode
        config:
          enabled: false
        # data volume is not required, since SQLite isn't used
        data:
          enabled: false
      env:
        # To enroll the Security Engine to the console
        - name: ENROLL_KEY
          value: "cltlvno6u0000l9087tnvut22"
        - name: ENROLL_INSTANCE_NAME
          value: "f9-k8s"
        - name: ENROLL_TAGS
          value: "k8s linux"
        - name: BOUNCER_KEY_traefik
          value: "mysecretkey12345"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crowdsec-secret
              key: DB_PASSWORD