apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
stringData:
    VIKUNJA_REDIS_PASSWORD: ENC[AES256_GCM,data:9av31h6SCrtsCdPyBA==,iv:S+ms9CYpcKltZZlPK1MhFXtZ7kzy2hoxIulICji2OKY=,tag:eRWsT5GMACRaWWFJrBhf8Q==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:1j/Zk8Zop2VZUAmGWb9pXw==,iv:3kDY4wslJXfUr41OSwRysJnBbzrPPa+sed5SerCZkwI=,tag:rHMzTFzLWLoBEAT0+D50Pg==,type:str]
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:CNh33zuTPQ2J60wTKRmsb2OSb69FwX5AGHFWLhg7qiSZ/YUXGrgt04mWs7U3qBjiQz5kO8trcalv+q7EFbEqZg3AHJ3XxyBTNSAnCxQi/rEm22IdSpsW+f1LafXpwzB1NT1UD1NvnCzyi1+31CqliyiCl3pyBLI+HRIgEA1M2zkDStX0ISuERqQcopzjOEAOBvBWtwneFhN23eP5Key7aqr/DL7e7dQVuk5GUlQZNLkan9H6LcH380qrvQ==,iv:odA1WexyJZMq4Urvkl0GWATJNLr57eWthXjEeFBJdX4=,tag:WB+9pVCH2jKLzUjc5FULEQ==,type:str]
    VIKUNJA_MAILER_HOST: ENC[AES256_GCM,data:apYGxAHUCjx81dCaBILbGYY=,iv:rGW1LfZUdkgJdZzxwNGOmID4FKBryjXmOEbtQjl1TnU=,tag:qiSVCw5uRRSab4sXQkZAVg==,type:str]
    VIKUNJA_MAILER_PORT: ENC[AES256_GCM,data:Gnuq,iv:MFXZy5leZgITIx3NCrEGfAR0uN9EIhjFj5EExPKJCMo=,tag:voB8fxK4dJYfh2RXlqkuKQ==,type:str]
    VIKUNJA_MAILER_AUTHTYPE: ENC[AES256_GCM,data:XAaV6XM=,iv:mgew4MGGR4e2/p6l4DmC4/SFTpQEEDRMRCwRI2c6V7M=,tag:2EDvTzLbwedjCZE/WcLeZA==,type:str]
    VIKUNJA_MAILER_USERNAME: ENC[AES256_GCM,data:EeWveBJJyRIKuTMqmXpUqLWD7XEWz4vKFmMRaa8PxQc=,iv:JBN2yjgZeOq7zCJeD4mBbxrDgOY1ihE8uNeLtGuN9nI=,tag:ZM/Ijl/qT/YG0U5CkgMfTw==,type:str]
    VIKUNJA_MAILER_PASSWORD: ENC[AES256_GCM,data:qnXkglwLhTaQuMlCeIa3HklhePgZE121r82mKE5bsAo=,iv:Cp7PqPdzN7ryxO+5wbLNyaBtoZ8nJBLIdTWbu3EE21o=,tag:g0IKPbflXy6MbxPrR0lYMA==,type:str]
    VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:5Qu3NiSLeYcnGL2u,iv:1+lnxs9D0THD9acElPhVYfVpgVOge4qEuDt1qxsS95o=,tag:d7KmZeqfcEv0ESFKVlh+Qw==,type:str]
    VIKUNJA_METRICS_USERNAME: ENC[AES256_GCM,data:j/JUD0PQ,iv:et76vvkzTK1mFr9DTJUe+2eJOnF0i1uH/pUEpcWpwKY=,tag:HGPseHNodcAoC5N9wr/Q9w==,type:str]
    VIKUNJA_METRICS_PASSWORD: ENC[AES256_GCM,data:ilPxGe+7JzJ7M0+k+iZK+9C6UqSlkWrGmHtfWg==,iv:6ah43SizD+a+7eJkUwUisLi8yflnsN36YngOQdgE7Xg=,tag:JBJxUGxGr0hmUHQbMF6H7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3NzL0RMSTJFVnBheVBJ
            TWJsNTV4RnIvRDZVV1FPNWk4RGdRZmtOR2tzCnZVblA4V2ZaOFc4RWxzNVc0NjZL
            MWw0ZENncWVjWVI2dkhQNERZZVhQcTgKLS0tIGlGckc5WXJ3RzJQbWppaEc3SUU1
            MnFtMXRIVkRNNmJyMXRac0xMdDNqbkkKecERsKHLyesvVYLEr+CoFeCnAASaY1V6
            sJbkndzmI9tG9Z08P2JN8qRYAMBXekG0xof4OLvPgGIg8TzsdqgdKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T20:49:27Z"
    mac: ENC[AES256_GCM,data:h8Dsxm1oiE1i4zBwqXlRr57WVGUHB0lDos20KkdA178zNiZiW/PaL2E9xdLCLWL5qFaWz9l94dxMlZjxSO+N8lxgUGUhL+qD2Jk9sH/ausw7hVeUu1jx2WmwTGO8W1suZAgt6evXOnlC9u4RXtI5Pg12VJ/8ikPAAh2k8gqX12g=,iv:1S82QSePQQnOISt1KbIVrQuc6elqIUqdhWkbFl94bHE=,tag:HVORJevxd3eiIAG29fKNGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 
